packages:
  - 'packages/*'

catalog:
  "@aws-sdk/client-dynamodb": "^3.1003.0"
  "@aws-sdk/client-sns": "^3.1003.0"
  "@discordjs/builders": "^1.13.1"
  "@discordjs/rest": "^2.6.0"
  "@napi-rs/canvas": "^0.1.88"
  "@rsc-sage/data-layer": "./packages/data-layer"
  "@rsc-sage/env": "./packages/sage-env"
  "@rsc-sage/localization": "./packages/sage-localization"
  "@rsc-utils/cache-utils": "github:rpg-sage-creative/cache-utils#semver:^1.1.0"
  "@rsc-utils/color-utils": "github:rpg-sage-creative/color-utils#semver:^1.1.0"
  "@rsc-utils/core-utils": "github:rpg-sage-creative/core-utils#semver:^1.6.0"
  "@rsc-utils/dev-scripts": "github:rpg-sage-creative/dev-scripts#semver:^1.4.2"
  "@rsc-utils/discord-utils": "github:rpg-sage-creative/discord-utils#semver:^1.4.0"
  "@rsc-utils/game-utils": "./packages/game-utils"
  "@rsc-utils/git-utils": "github:rpg-sage-creative/git-utils#semver:^0.1.0"
  "@rsc-utils/id-utils": "github:rpg-sage-creative/id-utils#semver:^1.1.0"
  "@rsc-utils/io-utils": "github:rpg-sage-creative/io-utils#semver:^1.5.1"
  "@rsc-utils/iterator-utils": "github:rpg-sage-creative/iterator-utils#semver:^1.1.0"
  "@rsc-utils/json-utils": "github:rpg-sage-creative/json-utils#semver:^1.2.1"
  "@rsc-utils/language-utils": "github:rpg-sage-creative/language-utils#semver:^1.2.0"
  "@rsc-utils/map-utils": "./packages/map-utils"
  "@rsc-utils/random-utils": "github:rpg-sage-creative/random-utils#semver:^0.1.1"
  "@rsc-utils/template-literal-utils": "github:rpg-sage-creative/template-literal-utils#semver:^1.2.0"
  "@rsc-utils/type-utils": "github:rpg-sage-creative/type-utils#semver:^1.3.0"
  "@rsc-utils/whitespace-utils": "github:rpg-sage-creative/whitespace-utils#semver:^1.0.0"
  "@types/follow-redirects": "^1.14.4"
  "@types/jest": "^30.0.0"
  "@types/node": "^24.12.0"
  "discord-api-types": "^0.38.41"
  "discord.js": "^14.26.2"
  "csv-parser": "^3.2.0"
  "emoji-regex-xs": "^2.0.1"
  "exifreader": "^4.36.2"
  "follow-redirects": "^1.15.11"
  "jest": "^30.2.0"
  "pdf2json": "^4.0.2"
  "regex": "^6.1.0"
  "stoat.js": "^7.3.6"
  "typescript": "^5.9.3"
  "zlib-sync": "^0.1.10"