import type { Proficiency } from "./Proficiency.js";

export type Proficiencies = {
	classDC: Proficiency;
	perception: Proficiency;
	fortitude: Proficiency;
	reflex: Proficiency;
	will: Proficiency;
	heavy: Proficiency;
	medium: Proficiency;
	light: Proficiency;
	unarmored: Proficiency;
	advanced: Proficiency;
	martial: Proficiency;
	simple: Proficiency;
	unarmed: Proficiency;
	castingArcane: Proficiency;
	castingDivine: Proficiency;
	castingOccult: Proficiency;
	castingPrimal: Proficiency;
	acrobatics: Proficiency;
	arcana: Proficiency;
	athletics: Proficiency;
	crafting: Proficiency;
	deception: Proficiency;
	diplomacy: Proficiency;
	intimidation: Proficiency;
	medicine: Proficiency;
	nature: Proficiency;
	occultism: Proficiency;
	performance: Proficiency;
	religion: Proficiency;
	society: Proficiency;
	stealth: Proficiency;
	survival: Proficiency;
	thievery: Proficiency;
};