export const ClimateCold = "A cold climate is found in the extreme northern or southern regions of the world at latitudes greater than 60 degrees (approximately 2,000 miles from a pole). In these polar regions, temperatures often remain below freezing throughout the majority of the year. The baseline temperature in this climate is cold, ranging from 20o F in the winter, to 30o F in the spring and fall months, and up to 40o F in the summer. For regions within 500 miles of the pole, the baseline temperature is 10o F colder than the seasonal average. For regions within 250 miles of the pole, the baseline temperature is 20o F colder than the seasonal average. Because cold air tends to be drier than warm air, reduce the frequency and intensity of precipitation by one step in cold climates (see page 167).";
export const ClimateTemperate = "Temperate climates stretch between the polar regions and tropical regions of the world, generally at latitudes between 60 degrees and 30 degrees. The baseline temperature in this climate ranges from 30o F in winter, to 60o F in spring and fall, and all the way up to 80o F in summer. Precipitation frequency is not altered as a result of a temperate climate, but it can still be altered as a result of other factors such as the elevation or season (see below).";
export const ClimateTropical = "The tropics exist to either side of the world's equator, extending north and south for about 30 degrees of latitude in either direction. Tropical regions tend to be warm and humid, with a baseline temperature ranging from 50o F in winter, to 75o F in spring and fall, and up to 95o F in summer. Because warm, humid air produces a great deal of precipitation, increase the frequency and intensity of precipitation by one step in this climate (see page 167).";

export const ElevationSeaLevel = "Temperatures in sea-level and coastal regions are 10o warmer. Sea-level regions also tend to have more precipitation than areas of higher elevation, so the baseline precipitation intensity in a sea-level region is heavy.";
export const ElevationLowland = "Lowlands are areas of low elevation not near the coast, generally at an elevation of 1,000 to 5,000 feet. This elevation range does not alter baseline temperatures. The baseline precipitation intensity in lowlands is medium.";
export const ElevationHighland = "Highlands include regions with elevations above 5,000 feet. Decrease baseline temperatures in highlands by 10o (although in particularly arid and flat regions, you should instead increase the baseline temperature by 10o, while in particularly high-altitude regions such as significant mountain ranges, you should instead decrease the baseline temperature by 20o). The frequency of precipitation is decreased by one step, and baseline precipitation intensity is medium.";

export const PrecipitationDrizzle = "Drizzle reduces visibility to three-quarters of the normal range, imposing a -2 penalty on Perception checks. It automatically extinguishes tiny unprotected flames (candles and the like, but not torches).";
export const PrecipitationHeavyFog = "Heavy fog obscures all vision beyond 5 feet, including darkvision. Creatures 5 feet away have concealment. Heavy fog typically occurs early in the day, late in the day, or sometimes at night, but the heat of the midday usually burns it away. Heavy fog occurs only when there is no or light wind.";
export const PrecipitationLightFog = "Light fog reduces visibility to three-quarters of the normal ranges, resulting in a -2 penalty on Perception checks and a -2 penalty on ranged attacks. Light fog typically occurs early in the day, late in the day, or sometimes at night, but the heat of the midday usually burns it away. Light fog occurs only when there is no or light wind.";
export const PrecipitationMediumFog = "Medium fog reduces visibility ranges by half, resulting in a -4 penalty on Perception checks and a -4 penalty on ranged attacks. Medium fog typically occurs early in the day, late in the day, or sometimes at night, but the heat of the midday usually burns it away. Medium fog occurs only when there is no or light wind.";
export const PrecipitationRain = "Rain reduces visibility ranges by half, resulting in a -4 penalty on Perception checks. Rain automatically extinguishes unprotected flames (candles, torches, and the like) and imposes a -4 penalty on ranged attacks.";
export const PrecipitationRainHeavy = "Heavy rain reduces visibility to one-quarter of the normal range, resulting in a -6 penalty on Perception checks. Heavy rain automatically extinguishes unprotected flames and imposes a -6 penalty on ranged attacks.";
export const PrecipitationSleet = "Essentially frozen rain, sleet has the same effect as light snow, but any accumulation typically doesn't last longer than 1-2 hours after the storm.";
export const PrecipitationSnowHeavy = "Heavy snow reduces visibility ranges to one- quarter of the normal range, resulting in a -6 penalty on Perception checks. It extinguishes unprotected flames and imposes a -6 penalty on ranged attacks. Heavy snow impedes movement even before it begins to stick. Moving into a square during a heavy snowstorm requires 1 extra 5-foot square of movement (this stacks with difficult terrain). Every hour of heavy snow leaves 1d4 inches of snow on the ground. As long as at least 2 inches of snow remain on the ground, the requirement of an extra square of movement to enter a square of snow persists. If at least 1 foot of snow remains on the ground, 2 extra squares of movement are required to enter a snow-filled square instead. A heavy snowstorm has a 10% chance of generating thundersnow (see page 171) and has a 40% chance of becoming a blizzard if the wind speed is severe or stronger.";
export const PrecipitationSnowLight = "Light snow reduces visibility to three- quarters of the normal range, resulting in a -2 penalty on Perception checks. Light snow has a 75% chance each hour of extinguishing unprotected flames and imposes a -2 penalty on ranged attacks. Light snow does not impede movement unless it continues for 2 or more hours, at which point moving into a square of such snow requires 1 extra 5-foot square of movement (this stacks with difficult terrain). Every 2 hours of light snow leaves 1 inch of snow on the ground. As long as at least 2 inches of snow remain on the ground, the requirement of an extra square of movement to enter a square of snow persists. If at least 1 foot of snow remains on the ground, entering a snow- filled square instead requires 2 extra squares of movement.";
export const PrecipitationSnowMedium = "Medium snow reduces visibility ranges by half, resulting in a -4 penalty on Perception checks. Medium snow extinguishes unprotected flames and imposes a -4 penalty on ranged attacks. Medium snow does not impede movement unless it continues for 1 hour, at which point moving into a square of such snow requires 1 extra 5-foot square of movement (this stacks with difficult terrain). Every hour of medium snow leaves 1 inch of snow on the ground. As long as at least 2 inches of snow remain on the ground, the requirement of an extra square of movement to enter a square of snow persists. If at least 1 foot of snow remains on the ground, entering a snow-filled square instead requires 2 extra squares of movement.";
export const PrecipitationThunderstorm = "Thunderstorms feature powerful winds (see page 170) and heavy rain (see above). To determine the type of wind associated with the thunderstorm, roll on Table 4-27: Thunderstorm Winds.<p/>In addition, there is a 40% chance that a thunderstorm features hail (see page 171) either up to an hour before or during the storm. An even greater danger presented by a thunderstorm is the lightning that occurs during the storm. These electrical discharges, generated by the roiling clouds, can pose a hazard to creatures that do not have proper shelters, especially creatures clad in metal armor. Every 10 minutes during a thunderstorm, a bolt of lightning strikes an unsheltered creature at random (though this can strike wildlife as easily as PCs). A creature struck by this lightning must succeed a DC 18 Reflex saving throw or take 10d8 points of electricity damage (a successful saving throw halves the damage). Creatures in metal armor take a -4 penalty on the Reflex saving throw.<p/>There is a 10% chance that a thunderstorm with winds of windstorm strength also generates a tornado (see page 171), while thunderstorms with windstorm-strength winds in temperatures higher than 85° F also have a 20% chance of being a precursor to a hurricane (see page 171). There is a 20% chance that a thunderstorm of any strength in the desert also generates a haboob (see page 171).";

export const SevereEventsBlizzard = "A combination of severe or stronger winds with heavy snow can create blizzard conditions. Blizzards reduce range of vision to no more than 20 feet, and even then, creatures takes a -8 penalty on Perception checks within that range. In a blizzard, the snowfall increases to 4 inches of snow each hour, and travel in more than 3 feet of snow is usually impossible without snowshoes or an ability such as waterwalk. Furthermore, the high winds make it feel (and affect living creatures) as if the temperature were 20° F colder. There is a 20% chance that a blizzard lasts for 2d12 hours instead of the normal duration for heavy snow.";
export const SevereEventsHaboob = "A haboob is a sandstorm created by a thunderstorm. See Sandstorm below for its effects.";
export const SevereEventsHail = "Hail typically occurs just before or during a thunderstorm (see page 169). Hail does not reduce visibility, but the sound of falling hail imposes a -4 penalty on sound- based Perception checks. Rarely (5% chance), hail pellets can become large enough to deal 1d4 points of lethal damage per minute to creatures and objects out in the open.";
export const SevereEventsHurricane = "Hurricanes are incredibly massive storms featuring heavy rain and a wind strength greater than that of the most powerful windstorm. With winds of 75-174 miles per hour, a hurricane renders ranged attacks impossible, and siege weapons take a -8 penalty on attack rolls. Large or smaller creatures must succeed at a DC 15 Strength check or they are unable to move forward against the strength of the wind. Medium or smaller creatures on the ground must succeed at a DC 15 Strength check or they are knocked prone and roll 1d6�10 feet, taking 1d6 points of nonlethal damage per 10 feet. Flying creatures must succeed at a DC 25 Fly check or they are blown back 2d8×10 feet and take 4d6 points of nonlethal damage due to battering and buffeting. Hurricanes also usually cause flooding. It's nearly impossible to journey out into a hurricane unscathed.";
export const SevereEventsSandstorm = "Sandstorms occur when severe or greater winds kick up sand and debris in a desert or similarly arid environment. Sandstorms reduce visibility to 1d10×10 feet, and those within them take a -6 penalty on Perception checks. Sandstorms deal 1d3 points of nonlethal damage per hour to creatures caught in the open.";
export const SevereEventsThundersnow = "High winds in a snowstorm can create the rare phenomena known as thundersnow. Lighting strikes are less common in thundersnow, but just as deadly. Every hour during the storm, a bolt of lightning strikes an unsheltered creature at random (though this can strike wildlife as easily as PCs). A creature struck by this lightning must succeed a DC 18 Reflex saving throw or take 10d8 points of electricity damage (a successful saving throw halves the damage). Creatures in metal armor take a -4 penalty on the Reflex saving throw.";
export const SevereEventsTornado = "With winds with speeds of 174-300 miles per hour, tornados are deadly terrors. The smallest tornados occupy a 20-foot-radius burst, with winds of windstorm strength swirling up to 100 feet beyond that burst. The largest tornados can be 100-foot-radius bursts, with a windstorm whose radius extends 500 feet beyond that burst. Ranged attacks, including normal, siege, and even those produced by evocation spells, are impossible in the core burst of a tornado. Huge or smaller creatures must succeed a DC 20 Strength check or be sucked up by the funnel of the tornado; this deals 8d8 points of bludgeoning, piercing, and slashing lethal damage to the creatures. This damage ignores all but DR/epic, DR/—, and hardness. Once it deals this damage, the tornado flings the creature it has sucked up 1d20×10 feet up and away from the tornado, dealing 1d6 points of falling damage per 10 feet that the creature is flung. Gargantuan and larger creatures take the 8d8 points of damage but are not moved by the tornado. A tornado moves at a speed of 40 feet, though the direction it moves is entirely unpredictable—you can determine the direction randomly each round. Tornados typically last for 3d6 minutes, but some can swirl for up to an hour.<p/>While most tornados are created by thunderstorms, some smaller tornados (typically with a 5- to 10-foot-burst radius, with no outer radius) can be created in areas of wildfire (firenados), snow (snownados), or sand (dust devils). They deal a similar amount of damage, but firenados deal fire damage, snownados deal cold damage, and dust devils deal bludgeoning damage only, and these types of tornados do not fling their targets.";
export const SevereEventsWildfire = "While wildfires can be sparked a number of ways, for these rules, they are usually created by a lightning strike in a particularly dry area of forest or other vegetation. Use the rules for forest fires (Pathfinder RPG Core Rulebook 426), but add a 10% chance of the fire producing 1d6 firenados (see Tornado above).";
