import type { PdfJsonFieldManager } from "@rsc-utils/io-utils";
import type { PdfKeyMap } from "../../sf2e/import/pdf/types.js";

export function getWanderersGuidePdfKeyMap(): PdfKeyMap { // NOSONAR
	const heritageParser = (_: PdfJsonFieldManager, value?: string) => {
		const heritage = value?.split("|")[0].trim();
		return !heritage ? undefined : heritage;
	};
	return new Map([
		// PDF Page 1

		/*
		XP
		Player_Name
		Heritage_and_Traits    "heritage | traits"
		Background_Notes
		Class_Notes
		CONDITIONS
		DEFENSE_NOTES
		SKILL_NOTES
		SPECIAL_MOVEMENT
		UNARMED_SIMPLE_ADVANCED_OTHER
		STRENGTH_PARTIAL_BOOST
		DEXTERITY_PARTIAL_BOOST
		CONSTITUTION_PARTIAL_BOODST
		INTELLIGENCE_PARTIAL_BOODST
		WISDOM_PARTIAL_BOOST
		CHARISMA_PARTIAL_BOOST
		DYING1
		DYING2
		DYING3
		DYING4
		*/

		// Character Basics
		["Character_Name", { sageKey: "name" }],
		["Ancestry", { sageKey: "ancestry" }],
		["Background", { sageKey: "background" }],
		["Class", { sageKey: "class" }],
		["Heritage_and_Traits", { sageKey: "heritage", valueParser: heritageParser }],
		["Size", { sageKey: "size" }],
		["LEVEL", { sageKey: "level" }],
		["RESISTANCE_AND_IMMUNITIES", { sageKey: "resistances" }],
		["LANGUAGES", { sageKey: "languages" }],
		["SENSES_AND_NOTES", { sageKey: "senses" }],
		["SPEED", { sageKey: "speed" }],
		["AC", { sageKey: "ac" }],

		// Character Health and Hero Points
		["MAXIMUM_HIT_POINTS", { sageKey: "maxHp" }],
		["Current_HP", { sageKey: "hp" }],
		["WOUNDED", { sageKey: "wounded" }],
		["Temporary_HP", { sageKey: "tempHp" }],
		["HERO_POINT_1", { sageKey: "heroPoint1", checked: true }],
		["HERO_POINT_2", { sageKey: "heroPoint2", checked: true }],
		["HERO_POINT_3", { sageKey: "heroPoint3", checked: true }],

		// Attributes
		["STRENGTH_STAT", { sageKey: "strMod" }],
		["DEXTERITY_STAT", { sageKey: "dexMod" }],
		["CONSTITUTION_STAT", { sageKey: "conMod" }],
		["INTELLIGENCE_STAT", { sageKey: "intMod" }],
		["WISDOM_STAT", { sageKey: "wisMod" }],
		["CHARISMA_STAT", { sageKey: "chaMod" }],

		// Saves
		["WILL", { sageKey: "willMod" }],
		["WISDOM", { sageKey: "willProfMod" }],
		["PROFICIENCY3", { sageKey: "willItemMod" }],
		["WILL_ITEM", { sageKey: "willWisMod" }],
		["WILL_TRAINED", { sageKey: "willTrained", checked: true }],
		["WILL_EXPERT", { sageKey: "willExpert", checked: true }],
		["WILL_MASTER", { sageKey: "willMaster", checked: true }],
		["WILL_LEGENDARY", { sageKey: "willLegendary", checked: true }],

		["REFLEX", { sageKey: "reflexMod" }],
		["DEXTERITY", { sageKey: "reflexDexMod" }],
		["PROFICIENCY2", { sageKey: "reflexProfMod" }],
		["ITEM2", { sageKey: "reflexItemMod" }],
		["REFLEX_TRAINED", { sageKey: "reflexTrained", checked: true }],
		["REFLEX_EXPERT", { sageKey: "reflexExpert", checked: true }],
		["REFLEX_MASTER", { sageKey: "reflexMaster", checked: true }],
		["REFLEX_LEGENDARY", { sageKey: "reflexLegendary", checked: true }],

		["FORTITUDE", { sageKey: "fortitudeMod" }],
		["CONSTITUTION", { sageKey: "fortitudeConMod" }],
		["PROFICIENCY", { sageKey: "fortitudeProfMod" }],
		["FORTITUDE_ITEM", { sageKey: "fortitudeItemMod" }],
		["FORTITUDE_TRAINED", { sageKey: "fortitudeTrained", checked: true }],
		["FORTITUDE_EXPERT", { sageKey: "fortitudeExpert", checked: true }],
		["FORTITUDE_MASTER", { sageKey: "fortitudeMaster", checked: true }],
		["FORTITUDE_LEGENDARY", { sageKey: "fortitudeLegendary", checked: true }],

		// Armor and Shields
		["SHIELD", { sageKey: "shieldMod" }],
		["AC_CALCULATION_1_DEXTERITY", { sageKey: "acDexMod" }],
		["AC_CALCULATION_2_PROFICIENCY", { sageKey: "acProfMod" }],
		["AC_CALCULATION_3_ITEM", { sageKey: "acItemMod" }],
		["Hardness_Max_HP", { sageKey: "shieldHardness" }],
		["MAX_HP", { sageKey: "shieldMaxHp" }],
		// ["shield_broken_threshold", { sageKey: "shieldBreakThreshold" }],
		["HP", { sageKey: "shieldHp" }],

		// Armor Proficiencies:
		["UNARMORED_TRAINED", { sageKey: "unarmoredTrained", checked: true }],
		["UNARMORED_EXPERT", { sageKey: "unarmoredExpert", checked: true }],
		["UNARMORED_MASTER", { sageKey: "unarmoredMaster", checked: true }],
		["UNARMORED_LEGENDARY", { sageKey: "unarmoredLegendary", checked: true }],

		["LIGHT_TRAINED", { sageKey: "lightArmorTrained", checked: true }],
		["LIGHT_EXPERT", { sageKey: "lightArmorExpert", checked: true }],
		["LIGHT_MASTER", { sageKey: "lightArmorMaster", checked: true }],
		["LIGHT_LEGENDARY", { sageKey: "lightArmorLegendary", checked: true }],

		["MEDIUM_TRAINED", { sageKey: "mediumArmorTrained", checked: true }],
		["MEDIUM_EXPERT", { sageKey: "mediumArmorExpert", checked: true }],
		["MEDIUM_MASTER", { sageKey: "mediumArmorMaster", checked: true }],
		["MEDIUM_LEGENDARY", { sageKey: "mediumArmorLegendary", checked: true }],

		["HEAVY_TRAINED", { sageKey: "heavyArmorTrained", checked: true }],
		["HEAVY_EXPERT", { sageKey: "heavyArmorExpert", checked: true }],
		["HEAVY_MASTER", { sageKey: "heavyArmorMaster", checked: true }],
		// ["ac_heavy_legendary", { sageKey: "heavyArmorLegendary", checked: true }], // pdf has MEDIUM_LEGENDARY

		// Skills, Perception, and DCs
		["CLASS_DC", { sageKey: "classDc" }],
		["CLASS_DC_KEY", { sageKey: "classDcAbilityMod" }],
		["CLASS_DC_PROFICIENCY", { sageKey: "classDcProfMod" }],
		["CLASS_DC_ITEM", { sageKey: "classDcItemMod" }],

		["ACROBATICS", { sageKey: "acrobaticsMod" }],
		["ACROBATICS_PROFICIENCY", { sageKey: "acrobaticsProfMod" }],
		["ACROBATICS_ITEM", { sageKey: "acrobaticsItemMod" }],
		["ACROBATICS_ARMOR", { sageKey: "acrobaticsArmorMod" }],
		["ACROBATICS_DEXTERITY", { sageKey: "acrobaticsDexMod" }],
		["ACROBATICS_TRAINED", { sageKey: "acrobaticsTrained", checked: true }],
		["ACROBATICS_EXPERT", { sageKey: "acrobaticsExpert", checked: true }],
		["ACROBATICS_MASTER", { sageKey: "acrobaticsMaster", checked: true }],
		["ACROBATICS_LEGENDARY", { sageKey: "acrobaticsLegendary", checked: true }],

		["ARCANA", { sageKey: "arcanaMod" }],
		["ARCANA_INTELLIGENCE", { sageKey: "arcanaIntMod" }],
		["ARCANA_PROFICIENCY", { sageKey: "arcanaProfMod" }],
		["ARCANA_ITEM", { sageKey: "arcanaItemMod" }],
		["ARCANA_TRAINED", { sageKey: "arcanaTrained", checked: true }],
		["ARCANA_EXPERT", { sageKey: "arcanaExpert", checked: true }],
		["ARCANA_MASTER", { sageKey: "arcanaMaster", checked: true }],
		// ["arcana_prof_legendary", { sageKey: "arcanaLegendary", checked: true }],

		["ATHLETICS", { sageKey: "athleticsMod" }],
		["ATHLETICS_STRENGTH", { sageKey: "athleticsStrMod" }],
		["ATHLETICS_PROFICIENCY", { sageKey: "athleticsProfMod" }],
		["ATHLETICS_ITEM", { sageKey: "athleticsItemMod" }],
		["ATHLETICS_ARMOR", { sageKey: "athleticsArmorMod" }],
		["ATHELETICS_TRAINED", { sageKey: "athleticsTrained", checked: true }],
		["ATHELETICS_EXPERT", { sageKey: "athleticsExpert", checked: true }],
		["ATHELETICS_MASTER", { sageKey: "athleticsMaster", checked: true }],
		["ATHELETICS_LEGENDARY", { sageKey: "athleticsLegendary", checked: true }],

		// ["computers", { sageKey: "computersMod" }],
		// ["computers_int_bonus", { sageKey: "computersIntMod" }],
		// ["computers_prof_bonus", { sageKey: "computersProfMod" }],
		// ["computers_item_bonus", { sageKey: "computersItemMod" }],
		// ["computers_prof_trained", { sageKey: "computersTrained", checked: true }],
		// ["computers_prof_expert", { sageKey: "computersExpert", checked: true }],
		// ["computers_prof_master", { sageKey: "computersMaster", checked: true }],
		// ["computers_prof_legendary", { sageKey: "computersLegendary", checked: true }],

		["CRAFTING", { sageKey: "craftingMod" }],
		["CRAFTING_INTELLIGENCE", { sageKey: "craftingIntMod" }],
		["CRAFTING_PROFICIENCY", { sageKey: "craftingProfMod" }],
		["CRAFTING_ITEM", { sageKey: "craftingItemMod" }],
		["CRAFTING_TRAINED", { sageKey: "craftingTrained", checked: true }],
		["CRAFTING_EXPERT", { sageKey: "craftingExpert", checked: true }],
		["CRAFTING_MASTER", { sageKey: "craftingMaster", checked: true }],
		["CRAFTING_LEGENDARY", { sageKey: "craftingLegendary", checked: true }],

		["DECEPTION", { sageKey: "deceptionMod" }],
		["DECEPTION_CHARISMA", { sageKey: "deceptionChaMod" }],
		["DECEPTION_PROFICIENCY", { sageKey: "deceptionProfMod" }],
		["DECEPTION_ITEM", { sageKey: "deceptionItemMod" }],
		["DECEPTION_TRAINED", { sageKey: "deceptionTrained", checked: true }],
		["DECEPTION_EXPERT", { sageKey: "deceptionExpert", checked: true }],
		["DECEPTION_MASTER", { sageKey: "deceptionMaster", checked: true }],
		["DECEPTION_LEGENDARY", { sageKey: "deceptionLegendary", checked: true }],

		["DIPLOMACY", { sageKey: "diplomacyMod" }],
		["DIPLOMACY_CHARISMA", { sageKey: "diplomacyChaMod" }],
		["DIPLOMACY_PROFICIENCY", { sageKey: "diplomacyProfMod" }],
		["DIPLOMACY_ITEM", { sageKey: "diplomacyItemMod" }],
		["DIPLOMACY_TRAINED", { sageKey: "diplomacyTrained", checked: true }],
		["DIPLOMACY_EXPERT", { sageKey: "diplomacyExpert", checked: true }],
		["DIPLOMACY_MASTER", { sageKey: "diplomacyMaster", checked: true }],
		["DIPLOMACY_LEGENDARY", { sageKey: "diplomacyLegendary", checked: true }],

		["INTIMIDATION", { sageKey: "intimidationMod" }],
		["INTIMIDATION_CHARISMA", { sageKey: "intimidationChaMod" }],
		["INTIMIDATION_PROFICIENCY", { sageKey: "intimidationProfMod" }],
		["INTIMIDATION_ITEM", { sageKey: "intimidationItemMod" }],
		["INTIMIDATION_TRAINED", { sageKey: "intimidationTrained", checked: true }],
		["INTIMIDATION_EXPERT", { sageKey: "intimidationExpert", checked: true }],
		["INTIMIDATION_MASTER", { sageKey: "intimidationMaster", checked: true }],
		["INTIMIDATION_LEGENDARY", { sageKey: "intimidationLegendary", checked: true }],

		["LORE_CATAGORY_1", { sageKey: "lore1Name" }],
		["LORE1", { sageKey: "lore1Mod" }],
		["LORE_1_INTELLIGENCE", { sageKey: "lore1IntMod" }],
		["LORE_1_PFOCIENCY", { sageKey: "lore1ProfMod" }],
		["LORE_1_ITEM", { sageKey: "lore1ItemMod" }],
		["LORE1_TRAINED", { sageKey: "lore1Trained", checked: true }],
		["LORE1_EXPERT", { sageKey: "lore1Expert", checked: true }],
		["LORE1_MASTER", { sageKey: "lore1Master", checked: true }],
		["LORE1_LEGENDARY", { sageKey: "lore1Legendary", checked: true }],

		["LORE_CATEGORY_2", { sageKey: "lore2Name" }],
		["LORE2", { sageKey: "lore2Mod" }],
		["LORE_CATEGORY_2_ITENLLIGENCE", { sageKey: "lore2IntMod" }],
		["LORE_2_PROFICIENCY", { sageKey: "lore2ProfMod" }],
		["LORE_2_ITEM", { sageKey: "lore2ItemMod" }],
		["LORE2_TRAINED", { sageKey: "lore2Trained", checked: true }],
		["LORE2_EXPERT", { sageKey: "lore2Expert", checked: true }],
		["LORE2_MASTER", { sageKey: "lore2Master", checked: true }],
		["LORE2_LEGENDARY", { sageKey: "lore2Legendary", checked: true }],

		["MEDICINE", { sageKey: "medicineMod" }],
		["MEDICINE_WISDOM", { sageKey: "medicineWisMod" }],
		["MEDICINE_PROFICIENCY", { sageKey: "medicineProfMod" }],
		["MEDICINE_ITEM", { sageKey: "medicineItemMod" }],
		["MEDECINE_TRAINED", { sageKey: "medicineTrained", checked: true }],
		["MEDICINE_EXPERT", { sageKey: "medicineExpert", checked: true }],
		["MEDICINE_MASTER", { sageKey: "medicineMaster", checked: true }],
		["MEDICINE_LEGENDARY", { sageKey: "medicineLegendary", checked: true }],

		["NATURE", { sageKey: "natureMod" }],
		["NATURE_WISDOM", { sageKey: "natureWisMod" }],
		["NATURE_PROFICIENCY", { sageKey: "natureProfMod" }],
		["NATURE_ITEM", { sageKey: "natureItemMod" }],
		["NATURE_TRAINED", { sageKey: "natureTrained", checked: true }],
		["NATURE_EXPERT", { sageKey: "natureExpert", checked: true }],
		["NATURE_MASTER", { sageKey: "natureMaster", checked: true }],
		["NATURE_LEGENDARY", { sageKey: "natureLegendary", checked: true }],

		["OCCULTISM", { sageKey: "occultismMod" }],
		["OCCULTISM_INTELLIGENCE", { sageKey: "occultismIntMod" }],
		["OCCULTISM_PROFICIENCY", { sageKey: "occultismProfMod" }],
		["OCCULTISM_ITEM", { sageKey: "occultismItemMod" }],
		["OCCULTISM_TRAINED", { sageKey: "occultismTrained", checked: true }],
		["OCCULTISM_EXPERT", { sageKey: "occultismExpert", checked: true }],
		["OCCULTISM_MASTER", { sageKey: "occultismMaster", checked: true }],
		["OCCULTISM_LEGENDARY", { sageKey: "occultismLegendary", checked: true }],

		["PERFORMANCE", { sageKey: "performanceMod" }],
		["PERFORMANCE_CHARISMA", { sageKey: "performanceChaMod" }],
		["PERFORMANCE_PROFICIENCY", { sageKey: "performanceProfMod" }],
		["PERFORMANCE_ITEM", { sageKey: "performanceItemMod" }],
		["PERFORMANCE_TRAINED", { sageKey: "performanceTrained", checked: true }],
		// ["performance_prof_expert", { sageKey: "performanceExpert", checked: true }], // OCCULTISM_EXPERT
		// ["performance_prof_master", { sageKey: "performanceMaster", checked: true }], // OCCULTISM_MASTER
		// ["performance_prof_legendary", { sageKey: "performanceLegendary", checked: true }], // OCCULTISM_LEGENDARY

		// ["piloting", { sageKey: "pilotingMod" }],
		// ["piloting_dex_bonus", { sageKey: "pilotingDexMod" }],
		// ["piloting_prof_bonus", { sageKey: "pilotingProfMod" }],
		// ["piloting_item_bonus", { sageKey: "pilotingItemMod" }],
		// ["piloting_prof_trained", { sageKey: "pilotingTrained", checked: true }],
		// ["piloting_prof_expert", { sageKey: "pilotingExpert", checked: true }],
		// ["piloting_prof_master", { sageKey: "pilotingMaster", checked: true }],
		// ["piloting_prof_legendary", { sageKey: "pilotingLegendary", checked: true }],

		["RELIGION", { sageKey: "religionMod" }],
		["RELIGION_WISDOM", { sageKey: "religionWisMod" }],
		["RELIGION_PROFICIENCY", { sageKey: "religionProfMod" }],
		["RELIGION_ITEM", { sageKey: "religionItemMod" }],
		["RELIGION_TRAINED", { sageKey: "religionTrained", checked: true }],
		["RELIGION_EXPERT", { sageKey: "religionExpert", checked: true }],
		["RELIGION_MASTER", { sageKey: "religionMaster", checked: true }],
		["RELIGION_LEGENDARY", { sageKey: "religionLegendary", checked: true }],

		["SOCIETY", { sageKey: "societyMod" }],
		["SOCIETY_INTELLIGENCE", { sageKey: "societyIntMod" }],
		["SOCIETY_PROFICIENCY", { sageKey: "societyProfMod" }],
		["SOCIETY_ITEM", { sageKey: "societyItemMod" }],
		["SOCIETY_TRAINED", { sageKey: "societyTrained", checked: true }],
		["SOCIETY_EXPERT", { sageKey: "societyExpert", checked: true }],
		["SOCIETY_MASTER", { sageKey: "societyMaster", checked: true }],
		["SOCIETY_LEGENDARY", { sageKey: "societyLegendary", checked: true }],

		["STEALTH", { sageKey: "stealthMod" }],
		["STEALTH_DEXTERITY", { sageKey: "stealthDexMod" }],
		["STEALTH_PROFICIENCY", { sageKey: "stealthProfMod" }],
		["STEALTH_ITEM", { sageKey: "stealthItemMod" }],
		["STEALTH_ARMOR", { sageKey: "stealthArmorMod" }],
		["STEALTH_TRAINED", { sageKey: "stealthTrained", checked: true }],
		["STEALTH_EXPERT", { sageKey: "stealthExpert", checked: true }],
		["STEALTH_MASTER", { sageKey: "stealthMaster", checked: true }],
		["STEALTH_LEGENDARY", { sageKey: "stealthLegendary", checked: true }],

		["SURVIVAL", { sageKey: "survivalMod" }],
		["SURVIVAL_WISDOM", { sageKey: "survivalWisMod" }],
		["SURVIVAL_PROFICIENCY", { sageKey: "survivalProfMod" }],
		["SURVIVAL_ITEM", { sageKey: "survivalItemMod" }],
		["SURVIVAL_TRAINED", { sageKey: "survivalTrained", checked: true }],
		["SURVIVAL_EXPERT", { sageKey: "survivalExpert", checked: true }],
		["SURVIVAL_MASTER", { sageKey: "survivalMaster", checked: true }],
		["SURVIVAL_LEGENDARY", { sageKey: "survivalLegendary", checked: true }],

		["THIEVERY", { sageKey: "thieveryMod" }],
		["THIEVERY_DEXTERITY", { sageKey: "thieveryDexMod" }],
		["THIEVERY_PROFICIENCY", { sageKey: "thieveryProfMod" }],
		["THIEVERY_ITEM", { sageKey: "thieveryItemMod" }],
		["THIEVERY_ARMOR", { sageKey: "thieveryArmorMod" }],
		["THIEVERY_TRAINED", { sageKey: "thieveryTrained", checked: true }],
		["THIEVERY_EXPERT", { sageKey: "thieveryExpert", checked: true }],
		["THIEVERY_MASTER", { sageKey: "thieveryMaster", checked: true }],
		["THIEVERY_LEGENDARY", { sageKey: "thieveryLegendary", checked: true }],

		["PERCEPTION", { sageKey: "perceptionMod" }],
		["PERCEPTION_WISDOM", { sageKey: "perceptionWisMod" }],
		["PERCEPTION_PROFICIENCY", { sageKey: "perceptionProfMod" }],
		["PERCEPTION_ITEM", { sageKey: "perceptionItemMod" }],
		["PERCEPTION_TRAINED", { sageKey: "perceptionTrained", checked: true }],
		["PERCEPTION_EXPERT", { sageKey: "perceptionExpert", checked: true }],
		["PERCEPTION_MASTER", { sageKey: "perceptionMaster", checked: true }],
		["PERCEPTION_LEGENDARY", { sageKey: "perceptionLegendary", checked: true }],

		// Attacks

		// Melee
		["MELEE_STRIKE_1", { sageKey: "melee1Name" }],
		["MELEE_STRIKE_1_STRENGTH", { sageKey: "melee1StrMod" }],
		["MELEE_STRIKE_1_PROFICIENCY", { sageKey: "melee1ProfMod" }],
		["MELEE_STRIKE_1_ITEM", { sageKey: "melee1ItemMod" }],
		["MELEE_STRIKE_1_ATTACK_BONUS", { sageKey: "melee1Mod" }],
		["MELEE_STRIKE_1_TRAITS_AND_NOTES", { sageKey: "melee1Traits" }],
		["MELEE_STRIKE_1_DAMAGE", { sageKey: "melee1Damage" }],

		["MELEE_STRIKE_2", { sageKey: "melee2Name" }],
		["MELEE_STRIKE_2_STRENGTH", { sageKey: "melee2StrMod" }],
		["MELEE_STRIKE_2_PROFICIENCY", { sageKey: "melee2ProfMod" }],
		["MELEE_STRIKE_2_ITEM", { sageKey: "melee2ItemMod" }],
		["MELEE_STRIKE_2_ATTACK_BONUS", { sageKey: "melee2Mod" }],
		["MELEE_STRIKE_2_TRAITS_AND_NOTES", { sageKey: "melee2Traits" }],
		["MELEE_STRIKE_2_DAMAGE", { sageKey: "melee2Damage" }],

		["MELEE_STRIKE_3", { sageKey: "melee3Name" }],
		["MELEE_STRIKE_3_STRENGTH", { sageKey: "melee3StrMod" }],
		["MELEE_STRIKE_3_PROFICIENCY", { sageKey: "melee3ProfMod" }],
		["MELEE_STRIKE_3_ITEM_BONUS", { sageKey: "melee3ItemMod" }],
		["MELEE_STRIKE_3_ATTACK_BONUS", { sageKey: "melee3Mod" }],
		["MELEE_STRIKE_3_TRAITS_AND_NOTES", { sageKey: "melee3Traits" }],
		["MELEE_STRIKE_3_DAMAGE", { sageKey: "melee3Damage" }],

		// Ranged
		["RANGED_STRIKE_4", { sageKey: "ranged1Name" }],
		["RANGED_STRIKE_4_PROFICIENCY", { sageKey: "ranged1ProfMod" }],
		["RANGED_STRIKE_4_DEXTERITY", { sageKey: "ranged1DexMod" }],
		["RANGED_STRIKE_4_ITEM_BONUS", { sageKey: "ranged1ItemMod" }],
		["RANGED_STRIKE_4_ATTACK_BONUS", { sageKey: "ranged1Mod" }],
		["RANGED_STRIKE_4_DAMAGE", { sageKey: "ranged1Damage" }],
		["RANGED_STRIKE_4_TRAITS_AND_NOTES", { sageKey: "ranged1Traits" }],

		["RANGED_STRIKE_5", { sageKey: "ranged2Name" }],
		["RANGED_STRIKE_5_PROFICIENCY", { sageKey: "ranged2ProfMod" }],
		["RANGED_STRIKE_5_DEXTERITY", { sageKey: "ranged2DexMod" }],
		["RANGED_STRIKE_5_ITEM", { sageKey: "ranged2ItemMod" }],
		["RANGED_STRIKE_5_ATTACK_BONUS", { sageKey: "ranged2Mod" }],
		["RANGED_STRIKE_5_DAMAGE", { sageKey: "ranged2Damage" }],
		["RANGED_STRIKE_5_TRAITS_AND_NOTES", { sageKey: "ranged2Traits" }],

		// Weapon Proficiencies:
		["UNARMED_TRAINED", { sageKey: "unarmedTrained", checked: true }],
		["UNARMED_EXPERT", { sageKey: "unarmedExpert", checked: true }],
		["UNARMED_MASTER", { sageKey: "unarmedMaster", checked: true }],
		["UNARMED_LEGENDARY", { sageKey: "unarmedLegendary", checked: true }],

		["SIMPLE_WEAPONS_TRAINED", { sageKey: "simpleTrained", checked: true }],
		["SIMPLE_WEAPONS_EXPERT", { sageKey: "simpleExpert", checked: true }],
		["SIMPLE_WEAPONS_MASTER", { sageKey: "simpleMaster", checked: true }],
		["SIMPLE_WEAPONS_LEGENDARY", { sageKey: "simpleLegendary", checked: true }],

		["MARTIAL_WEAPONS_TRAINED", { sageKey: "martialTrained", checked: true }],
		["MARTIAL_WEAPONS_EXPERT", { sageKey: "martialExpert", checked: true }],
		["MARTIAL_WEAPONS_MASTER", { sageKey: "martialMaster", checked: true }],
		["MARTIAL_WEAPONS_LEGEANDARY", { sageKey: "martialLegendary", checked: true }],

		["ADVANCED_WEAPON_TRAINED", { sageKey: "advancedTrained", checked: true }],
		["ADVANCED_WEAPON_EXPERT", { sageKey: "advancedExpert", checked: true }],
		["ADVANCED_WEAPON_MASTER", { sageKey: "advancedMaster", checked: true }],
		["ADVANCED_WEAPON_LEGENDARY", { sageKey: "advancedLegendary", checked: true }],

		// Spellcasting Modifiers:
		["SPELL_SAVE_DC_KEY", { sageKey: "spellDcAbilityMod" }],
		["SPELL_SAVE_DC_PROFICIENCY", { sageKey: "spellDcProfMod" }],
		["SPELL_ATTACK_KEY", { sageKey: "spellAttackAbilityMod" }],
		["SPELL_ATTACK_PROFICIENCY", { sageKey: "spellAttackProfMod" }],
		["SPELL_SAVE_DC", { sageKey: "spellDcMod" }],
		["SPELL_ATTACK", { sageKey: "spellAttackMod" }],
		["SPELL_SAVE_DC_TRAINED", { sageKey: "spellDcTrained", checked: true }],
		["SPELL_SAVE_DC_EXPERT", { sageKey: "spellDcExpert", checked: true }],
		["SPELL_SAVE_DC_MASTER", { sageKey: "spellDcMaster", checked: true }],
		["SPELL_SAVE_DC_LEGENDARY", { sageKey: "spellDcLegendary", checked: true }],
		["SPELL_ATTACK_TRAINED", { sageKey: "spellAttackTrained", checked: true }],
		["SPELL_ATTACK_EXPERT", { sageKey: "spellAttackExpert", checked: true }],
		["SPELL_ATTACK_MASTER", { sageKey: "spellAttackMaster", checked: true }],
		["SPELL_ATTACK_LEGENDARY", { sageKey: "spellAttackLegendary", checked: true }],

		["BULK_TOTAL", { sageKey: "bulk" }],
		["COPPER", { sageKey: "cp" }],
		["SILVER", { sageKey: "sp" }],
		["GOLD", { sageKey: "gp" }],
		["PLATINUM", { sageKey: "pp" }],
		// ["credits", { sageKey: "credits" }],
		// ["upb", { sageKey: "upb" }],
		// ["port_of_call", { sageKey: "portOfCall" }],
		["Appearance", { sageKey: "appearance" }],
		// ["homeworld", { sageKey: "homeworld" }],
		["AGE", { sageKey: "age" }],
		["GENDER_PRONOUNS", { sageKey: "pronouns" }],
		["HEIGHT", { sageKey: "height" }],
		["WEIGHT", { sageKey: "weight" }],
		["Attitude", { sageKey: "attitude" }],
		["Edicts", { sageKey: "edicts" }],
		["Deity_or_Philosophy", { sageKey: "philosophy" }],
		["Anathema", { sageKey: "anathema" }],
		["Likes", { sageKey: "likes" }],
		["Dislikes", { sageKey: "dislikes" }],
		["Catchphrases", { sageKey: "catchphrases" }],
		// ["campaign_notes", { sageKey: "campaignNotes" }],
		["Allies", { sageKey: "allies" }],
		["Enemies", { sageKey: "enemies" }],
		// ["faction", { sageKey: "faction" }],
		["SPELLS_PER_DAY_1", { sageKey: "spellsPerDay1" }],
		["SPELLS_PER_DAY_2", { sageKey: "spellsPerDay2" }],
		["SPELLS_PER_DAY_3", { sageKey: "spellsPerDay3" }],
		["SPELLS_PER_DAY_4", { sageKey: "spellsPerDay4" }],
		["SPELLS_PER_DAY_5", { sageKey: "spellsPerDay5" }],
		["SPELLS_PER_DAY_6", { sageKey: "spellsPerDay6" }],
		["SPELLS_PER_DAY_7", { sageKey: "spellsPerDay7" }],
		["SPELLS_PER_DAY_8", { sageKey: "spellsPerDay8" }],
		["SPELLS_PER_DAY_9", { sageKey: "spellsPerDay9" }],
		["SPELLS_PER_DAY_10", { sageKey: "spellsPerDay10" }],
		["SPELLS_REMAINING_1", { sageKey: "spellsRemaining1" }],
		["SPELLS_REMAINING_2", { sageKey: "spellsRemaining2" }],
		["SPELLS_REMAINING_3", { sageKey: "spellsRemaining3" }],
		["SPELLS_REMAINING_4", { sageKey: "spellsRemaining4" }],
		["SPELLS_REMAINING_5", { sageKey: "spellsRemaining5" }],
		["SPELLS_REMAINING_6", { sageKey: "spellsRemaining6" }],
		["SPELLS_REMAINING_7", { sageKey: "spellsRemaining7" }],
		["SPELLS_REMAINING_8", { sageKey: "spellsRemaining8" }],
		["SPELLS_REMAINING_9", { sageKey: "spellsRemaining9" }],
		["SPELLS_REMAINING_10", { sageKey: "spellsRemaining10" }],
		["CANTRIPS_RANK", { sageKey: "cantripRank" }],
		["CANTRIPS_PER_DAY", { sageKey: "cantripsPerDay" }],

		["CLASS_FEATS_FEATURES", { sageKey: "classFeatsFeatures" }],
		["ANCESTRY_HERITAGE_ABILITIES", { sageKey: "ancestryAbilities" }],
		["ANCESTRY_FEAT", { sageKey: "ancestryFeat1" }],
		["BACKGROUND_SKILL_FEAT", { sageKey: "backgroundFeat" }],
		["SKILL_FEAT_2_1", { sageKey: "skillFeat2" }],   // SKILL_FEAT_2_2, SKILL_FEAT_2_3
		["SKILL_FEAT_3_1", { sageKey: "generalFeat3" }],
		["SKILL_FEAT_4_1", { sageKey: "skillFeat4" }],
		["SKILL_FEAT_5_1", { sageKey: "ancestryFeat5" }],
		["SKILL_FEAT_6_1", { sageKey: "skillFeat6" }],
		["SKILL_FEAT_6_2", { sageKey: "generalFeat6" }],
		// [361, { sageKey: "skillFeat8" }],
		// [362, { sageKey: "ancestryFeat9" }],
		// [364, { sageKey: "generalFeat11" }],
		// [365, { sageKey: "skillFeat12" }],
		// [366, { sageKey: "ancestryFeat13" }],
		// [367, { sageKey: "skillFeat14" }],
		// [368, { sageKey: "skillFeat16" }],
		// [369, { sageKey: "ancestryFeat17" }],
		// [370, { sageKey: "skillFeat18" }],
		// [371, { sageKey: "generalFeat19" }],
		// [373, { sageKey: "classFeat2" }],
		// [374, { sageKey: "classFeature3" }],
		// [375, { sageKey: "classFeat4" }],
		// [376, { sageKey: "classFeature5" }],
		// [377, { sageKey: "classFeat6" }],
		// [378, { sageKey: "classFeature7" }],
		// [379, { sageKey: "classFeat8" }],
		// [380, { sageKey: "classFeature9" }],
		// [381, { sageKey: "classFeat10" }],
		// [382, { sageKey: "classFeature11" }],
		// [383, { sageKey: "classFeat12" }],
		// [384, { sageKey: "classFeature13" }],
		// [385, { sageKey: "classFeat14" }],
		// [386, { sageKey: "classFeature15" }],
		// [387, { sageKey: "classFeat16" }],
		// [388, { sageKey: "classFeature17" }],
		// [389, { sageKey: "classFeat18" }],
		// [390, { sageKey: "classFeature19" }],
		// [391, { sageKey: "classFeat20" }],
		// [392, { sageKey: "generalFeat15" }],
		// [394, { sageKey: "skillFeat10" }],
		// [395, { sageKey: "skillFeat20" }],
		// [396, { sageKey: "attributeBoosts20" }],
		// [397, { sageKey: "attributeBoosts15" }],
		// [398, { sageKey: "attributeBoosts10" }],
		// [399, { sageKey: "attributeBoosts5" }],
		["HELD1", { sageKey: "heldItem1" }],
		["HELD_2", { sageKey: "heldItem2" }],
		["HELD_3", { sageKey: "heldItem3" }],
		["HELD_4", { sageKey: "heldItem4" }],
		["HELD_5", { sageKey: "heldItem5" }],
		["HELD_6", { sageKey: "heldItem6" }],
		["HELD_7", { sageKey: "heldItem7" }],
		["HELD_8", { sageKey: "heldItem8" }],
		["HELD_9", { sageKey: "heldItem9" }],
		["HELD_10", { sageKey: "heldItem10" }],
		["HELD_11", { sageKey: "heldItem11" }],
		["HELD_BULK_1", { sageKey: "heldItem1Bulk" }],
		["HELD_BULK_2", { sageKey: "heldItem2Bulk" }],
		["HELD_BULK_3", { sageKey: "heldItem3Bulk" }],
		["HELD_BULK_4", { sageKey: "heldItem4Bulk" }],
		["HELD_BULK_5", { sageKey: "heldItem5Bulk" }],
		["HELD_BULK_6", { sageKey: "heldItem6Bulk" }],
		["HELD_BULK_7", { sageKey: "heldItem7Bulk" }],
		["HELD_BULK_8", { sageKey: "heldItem8Bulk" }],
		["HELD_BULK_9", { sageKey: "heldItem9Bulk" }],
		["HELD_BULK_10", { sageKey: "heldItem10Bulk" }],
		["HELD_BULK_11", { sageKey: "heldItem11Bulk" }],
		["CONSUMABLES_1", { sageKey: "consumableItem1" }],
		["CONSUMABLES_2", { sageKey: "consumableItem2" }],
		["CONSUMABLES_3", { sageKey: "consumableItem3" }],
		["CONSUMABLES_4", { sageKey: "consumableItem4" }],
		["CONSUMABLES_5", { sageKey: "consumableItem5" }],
		["CONSUMABLES_6", { sageKey: "consumableItem6" }],
		["CONSUMABLES_7", { sageKey: "consumableItem7" }],
		["CONSUMABLES_8", { sageKey: "consumableItem8" }],
		["CONSUMABLES_9", { sageKey: "consumableItem9" }],
		["CONSUMABLES_10", { sageKey: "consumableItem10" }],
		["CONSUMABLES_11", { sageKey: "consumableItem11" }],
		["CONSUMABLES_BULK_1", { sageKey: "consumableItem1Bulk" }],
		["CONSUMABLES_BULK_2", { sageKey: "consumableItem2Bulk" }],
		["CONSUMABLES_BULK_3", { sageKey: "consumableItem3Bulk" }],
		["CONSUMABLES_BULK_4", { sageKey: "consumableItem4Bulk" }],
		["CONSUMABLES_BULK_5", { sageKey: "consumableItem5Bulk" }],
		["CONSUMABLES_BULK_6", { sageKey: "consumableItem6Bulk" }],
		["CONSUMABLES_BULK_7", { sageKey: "consumableItem7Bulk" }],
		["CONSUMABLES_BULK_8", { sageKey: "consumableItem8Bulk" }],
		["CONSUMABLES_BULK_9", { sageKey: "consumableItem9Bulk" }],
		["CONSUMABLES_BULK_10", { sageKey: "consumableItem10Bulk" }],
		["CONSUMABLES_BULK_11", { sageKey: "consumableItem11Bulk" }],
		["WORN_1", { sageKey: "wornItem1" }],
		["WORN_2", { sageKey: "wornItem2" }],
		["WORN_3", { sageKey: "wornItem3" }],
		["WORN_4", { sageKey: "wornItem4" }],
		["WORN_5", { sageKey: "wornItem5" }],
		["WORN_6", { sageKey: "wornItem6" }],
		["WORN_7", { sageKey: "wornItem7" }],
		["WORN_8", { sageKey: "wornItem8" }],
		["WORN_9", { sageKey: "wornItem9" }],
		["WORN_10", { sageKey: "wornItem10" }],
		["WORN_11", { sageKey: "wornItem11" }],
		["WORN_12", { sageKey: "wornItem12" }],
		["WORN_13", { sageKey: "wornItem13" }],
		["WORN_14", { sageKey: "wornItem14" }],
		["WORN_15", { sageKey: "wornItem15" }],
		["WORN_16", { sageKey: "wornItem16" }],
		["WORN_17", { sageKey: "wornItem17" }],
		["WORN_18", { sageKey: "wornItem18" }],
		["WORN_19", { sageKey: "wornItem19" }],
		["INVESTED_1", { sageKey: "wornItem1Invested", checked: true }],
		["INVESTED_2", { sageKey: "wornItem2Invested", checked: true }],
		["INVESTED_3", { sageKey: "wornItem3Invested", checked: true }],
		["INVESTED_4", { sageKey: "wornItem4Invested", checked: true }],
		["INVESTED_5", { sageKey: "wornItem5Invested", checked: true }],
		["INVESTED_6", { sageKey: "wornItem6Invested", checked: true }],
		["INVESTED_7", { sageKey: "wornItem7Invested", checked: true }],
		["INVESTED_8", { sageKey: "wornItem8Invested", checked: true }],
		["INVESTED_9", { sageKey: "wornItem9Invested", checked: true }],
		["INVESTED_10", { sageKey: "wornItem10Invested", checked: true }],
		["INVESTED_12", { sageKey: "wornItem12Invested", checked: true }],
		["INVESTED_13", { sageKey: "wornItem13Invested", checked: true }],
		["INVESTED_14", { sageKey: "wornItem14Invested", checked: true }],
		["INVESTED_15", { sageKey: "wornItem15Invested", checked: true }],
		["INVESTED_16", { sageKey: "wornItem16Invested", checked: true }],
		["INVESTED_17", { sageKey: "wornItem17Invested", checked: true }],
		["INVESTED_18", { sageKey: "wornItem18Invested", checked: true }],
		["INVESTED_19", { sageKey: "wornItem19Invested", checked: true }],
		["WORN_BULK_1", { sageKey: "wornItem1Bulk" }],
		["WORN_BULK_2", { sageKey: "wornItem2Bulk" }],
		["WORN_BULK_3", { sageKey: "wornItem3Bulk" }],
		["WORN_BULK_4", { sageKey: "wornItem4Bulk" }],
		["WORN_BULK_5", { sageKey: "wornItem5Bulk" }],
		["WORN_BULK_6", { sageKey: "wornItem6Bulk" }],
		["WORN_BULK_7", { sageKey: "wornItem7Bulk" }],
		["WORN_BULK_8", { sageKey: "wornItem8Bulk" }],
		["WORN_BULK_9", { sageKey: "wornItem9Bulk" }],
		["WORN_BULK_10", { sageKey: "wornItem10Bulk" }],
		["WORN_BULK_11", { sageKey: "wornItem11Bulk" }],
		["WORN_BULK_12", { sageKey: "wornItem12Bulk" }],
		["WORN_BULK_13", { sageKey: "wornItem13Bulk" }],
		["WORN_BULK_14", { sageKey: "wornItem14Bulk" }],
		["WORN_BULK_15", { sageKey: "wornItem15Bulk" }],
		["WORN_BULK_16", { sageKey: "wornItem16Bulk" }],
		["WORN_BULK_17", { sageKey: "wornItem17Bulk" }],
		["WORN_BULK_18", { sageKey: "wornItem18Bulk" }],
		["WORN_BULK_19", { sageKey: "wornItem19Bulk" }],
		["GEMS_ART_1", { sageKey: "valuable1" }],
		["GEMS_ART_2", { sageKey: "valuable2" }],
		["GEMS_ART_3", { sageKey: "valuable3" }],
		["GEMS_ART_4", { sageKey: "valuable4" }],
		["GEMS_ART_5", { sageKey: "valuable5" }],
		["PRICE_1", { sageKey: "valuable1Price" }],
		["PRICE_2", { sageKey: "valuable2Price" }],
		["PRICE_3", { sageKey: "valuable3Price" }],
		["PRICE_4", { sageKey: "valuable4Price" }],
		["PRICE_5", { sageKey: "valuable5Price" }],
		["ART_BULK_1", { sageKey: "valuable1Bulk" }],
		["ART_BULK_2", { sageKey: "valuable2Bulk" }],
		["ART_BULK_3", { sageKey: "valuable3Bulk" }],
		["ART_BULK_4", { sageKey: "valuable4Bulk" }],
		["ART_BULK_5", { sageKey: "valuable5Bulk" }],

		["FOCUS_SPELL_RANK", { sageKey: "focusSpellRank" }],
		// [670, { sageKey: "spellNames" }],
		// [671, { sageKey: "spellNames2" }],
		// [672, { sageKey: "cantripNames" }],
		// [673, { sageKey: "cantripActions" }],
		// [675, { sageKey: "spellActions" }],
		// [676, { sageKey: "spellRanks" }],
		// [677, { sageKey: "spellActions2" }],
		// [678, { sageKey: "spellRanks2" }],
		// [679, { sageKey: "cantripPrepared" }],
		// [680, { sageKey: "spellPrepared" }],
		// [681, { sageKey: "spellPrepared2" }],
		// [682, { sageKey: "focusSpellNames" }],
		// [683, { sageKey: "focusSpellActions" }],
		// [684, { sageKey: "innateSpellNames" }],
		// [685, { sageKey: "innateSpellActions" }],
		// [686, { sageKey: "innateSpellFrequency" }],
		// [687, { sageKey: "ritualNames" }],
		// [688, { sageKey: "ritualRanks" }],
		// [689, { sageKey: "ritualCosts" }],
		// [690, { sageKey: "ritualRanks2" }],
		// [691, { sageKey: "ritualCosts2" }],
		// [692, { sageKey: "ritualNames2" }],

		//  TODO: These do not appear to have fields in the PDF as of now
		//  [181, { sageKey: "ranged2Range" }],
		//  [182, { sageKey: "ranged1Range" }],
		//  [183, { sageKey: "ranged3Range" }],
		//  [189, { sageKey: "ranged2Magazine" }],
		//  [190, { sageKey: "ranged2Expended" }],
		//  [191, { sageKey: "ranged1Magazine" }],
		//  [192, { sageKey: "ranged1Expended" }],
		//  [193, { sageKey: "ranged3Magazine" }],
		//  [194, { sageKey: "ranged3Expended" }],
		//  [196, { sageKey: "weaponProfNotes" }],
		 ["CRITICAL_SPECIALIZATIONS", { sageKey: "criticalSpecializations" }],
		//  [247, { sageKey: "otherTrained", checked: true }],
		//  [248, { sageKey: "otherExpert", checked: true }],
		//  [249, { sageKey: "otherMaster", checked: true }],
		//  [250, { sageKey: "otherLegendary", checked: true }],
	]);
}